### ISSUE TITLE
User is allowed to resign even after the other player has already resigned

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#114]
When the user clicks on the resign button prior to the other user’s resigning, the user can still opt to resign even after the previous game has ended.

Bug Report: https://docs.google.com/document/d/1w5SuOq9mgWZy8HFwr8gTKkPuGOz3ZyBcW-BQTDhUmp8/edit

**Comment by counterPH** [comment]
Issue is resolved.
