### ISSUE TITLE
Win Rate and Points reflected on the Waiting Room Page differs from the Profile Page

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#118]
Win Rate and Points are inconsistent as seen on the Waiting Room Page and the Profile Page.

Bug Report: https://docs.google.com/document/d/1PFZjEkcV9xYE5e5w7mkocQDUQkOye7ZDEHEWim38sis/edit

**Comment by counterPH** [comment]
Issue is resolved.
