### ISSUE TITLE
User is stuck in waiting for accept state after rejecting but not leaving

### ISSUE THREAD

**Issue by counterPH** [MaikaRenee/check-with-me#120]
After declining the invitation to rematch and choosing not to leave the game lobby page, both users are stuck in the game lobby page as the pop up modal for rematch on the player who chose to not leave the lobby did not appear.

Bug Report: https://docs.google.com/document/d/1ckrqznYdvSoOD1haZjLxTA8uRx2eNn45r0UAYS7vuhY/edit

**Comment by geosefuy** [comment]
Issue is resolved.
