### ISSUE TITLE
Invalid move on open green square is not considered

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#27]
When a normal piece is highlighted, and clicking on a certain green square, the piece highlight does not disappear, making it seem the move is not registered.

Bug Report: https://docs.google.com/document/d/1NE0_ZorbXVuh8Kl8skEOq8R9Yrrx6dMvRmeln3LqisA/edit

**Comment by counterPH** [comment]
Issue is resolved.
