### ISSUE TITLE
Page should fit to screen so user does not have to scroll

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#29]
When the page loads, in the QAs’ side, the page should not scroll so the user does not have to do it just to see the name, timer, and pieces left of the player at the bottom.

Bug Report: https://docs.google.com/document/d/1zL6EHObinoimWSfHghZbtRxjpSQpOjnGXp87yuWcX8k/edit

**Comment by counterPH** [comment]
Issue is resolved.
