### ISSUE TITLE
Checker piece is not deselected after clicking on it, then clicking on it again

### ISSUE THREAD

**Issue by counterPH** [MaikaRenee/check-with-me#31]
When selecting on a checker piece and after clicking on it once, clicking on it again doesn’t deselect the checker piece.

Suggestion Report: https://docs.google.com/document/d/1RGmgiceRC-gT1wwwxcIJsMpTijXdvjgkfUmQ-2LUKvw/edit?usp=sharing

**Comment by geosefuy** [comment]
Issue is resolved.
