### ISSUE TITLE
All the possible landing squares of the King checker piece is not highlighted

### ISSUE THREAD

**Issue by counterPH** [MaikaRenee/check-with-me#33]
When the King checker piece is selected with two or more possible landing squares for a capture move, only the open square located directly after the possible captured checker piece is highlighted.

Bug Report: https://docs.google.com/document/d/1LmbDMP2A1GL1T-_7bgpebpTlFek0pyzgP4ZbO1KLthA/edit?usp=sharing

**Comment by geosefuy** [comment]
Issue is resolved.
