### ISSUE TITLE
Highlight of King space after capture cannot be seen after making an invalid move

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#75]
After selecting the king piece, making an invalid move, and attempting to capture using said king, the highlighted space after capture cannot be seen anymore.

Bug Report: https://docs.google.com/document/d/1vOTuGr2gwqmh8hnJFZ_ls6Ev6p32XvzCHnH0ymcI24M/edit

**Comment by counterPH** [comment]
Issue is resolved.
