### ISSUE TITLE
Highlight of checker space after capture cannot be seen after making an invalid move

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#77]
After making an invalid move, and attempting to capture using said piece, the highlighted space after capture cannot be seen anymore.

Bug Report: https://docs.google.com/document/d/1pLL2YnRbtFB51Qr31yvdYgx8ZQERwDE2C27ztgWgZhI/edit

**Comment by counterPH** [comment]
Issue is resolved.
