### ISSUE TITLE
C.1 - UI - Misplaced Resign Button

### ISSUE THREAD

**Issue by gwyneth-ang** [MaikaRenee/check-with-me#83]
## Defect C.1
**Date:** Thursday,  14 Jan 2021
| | |
|-|-|
**Title** | UI - Misplaced Resign Button
**Description** | Resign button appears on top of the board. It only moves away from the board when the browser screen is zoomed out.
**Reporter** | Team GImmICK (Ang)
**Device/OS used** | Windows 10 - Google Chrome
**Prerequisite** | The user must be logged in to deployed site (https://check-with-me.web.app/#/)
**Priority Level** | Low

**Steps to Reproduce:** None. The resign button is seen once logged in.

**Expected Result:** 
- Button must not be on top of the board. 
![image](https://user-images.githubusercontent.com/60255879/104599561-eb7df500-56b2-11eb-90ac-666e466c3471.png)

- This is the zoomed out view *

**Actual Result:**
![](https://user-images.githubusercontent.com/60255879/104598649-c937a780-56b1-11eb-8d85-a42e184cf97c.png)

**Comment by carlosshi1** [comment]
Teampura confirms this on Microsoft Edge Version 87.0.664.75 (64-bit)
![image](https://user-images.githubusercontent.com/56996127/104726682-00b85980-576f-11eb-8a40-d76c7320e96e.png)

**Comment by Mscizor** [comment]
|  |  |
|-|-|
| Summary: | Resign button overlaps on playing board / not visible|
| Reporter: | Team Rocket |
| Browser: | Firefox Developer 85.0b6, Window Size: 1536 x 750 |
| OS: | Microsoft Windows 10 Pro |
| Expected Results: | Zooming in results in the resign button being pushed to the side |
| Actual Results: | Zooming in makes the resign button overlap the game, leading some squared unable to be clicked |
| Steps to Reproduce: | 1. Log in with a valid account<br>2. Zoom in to 110%<br>3. Zoom out to 30% |

![image](https://user-images.githubusercontent.com/19809794/104792918-267b4800-57db-11eb-8700-501a14a992ff.png)
![image](https://user-images.githubusercontent.com/19809794/104793148-3a737980-57dc-11eb-8aea-101ee89b034e.png)

**Comment by BrianJSo** [comment]
**Title/Summary:** (UI/UX) Resign button is on top of board for smaller screen size
**Description:** The resign button moves on top of the board when zooming in the screen or is already on top of the board for smaller screen sizes.
**Browser:** Google Chrome

**Steps to Reproduce:**
> 1. Zoom in the screen until resign button moves on top of the board, or
> 2. Change the screen size to less than 1530 px in width in browser developer tools.

**Actual results:** Resign button moves on top of the board.
**Expected results:** Resign button stays at the side of the board even in smaller screen sizes.
**Visual proof:** 
![image](https://user-images.githubusercontent.com/51768646/104835567-801a6a00-58e2-11eb-9a09-e6f6946afe30.png)
**Defect Report Date:** January 17, 2021

**Comment by RichardZapanta** [comment]
This is a valid bug. We will be fixing it on this sprint together with the resign feature. Thank you!

**Comment by counterPH** [comment]
Issue is resolved.
