### ISSUE TITLE
[Teampura#1] The state of the game does not reload when new user logs in

### ISSUE THREAD

**Issue by NeilMatthewLua** [MaikaRenee/check-with-me#89]
| | |
-|-
ID | Teampura#1
Title | The state of the game does not reload when new user logs in
Reporter | Neil Lua
Date | 1-15-21
Environment | Microsoft Edge Version 87.0.664.75 (Official build) (64-bit) Windows 10 Home 18363.1316

Description: 
After playing a game, then winning. I logged out and logged in as a new user, but the state of the recently finished game did not refresh

Steps to reproduce:
1. Log in as a user (Valid account)
2. Win the game
3. Log out 
4. Log in as a different user (Valid account)
5. Brings you to the game the last user played

Expected Result:
1. Game should not show the previous logged user's game

Actual Result:
1. Game shows the previous logged user's game

Attachments:
https://drive.google.com/file/d/1LmnAf1LnLfbOF3oFR91CUu-yi-sG19Zd/view?usp=sharing

**Comment by Mscizor** [comment]
|||
|-|-|
| Summary: | Finished game in one account is able to be seen on another |
| Reporter: | Team Rocket |
| Browser: | Firefox Developer 85.0b6, Window Size: 1536 x 750 |
| OS: | Microsoft Windows 10 Pro |
| Expected Results: | New game is able to be played on a different account after logging out the original |
| Actual Results: | Game from the original account is also able to be seen on the new logged in account |
| Steps to Reproduce: | 1. Log in with a valid account<br>2. Make Black win by moving all the pieces and blocking White's moves<br>3. Click exit to close the "Black Wins" modal<br>4. Click the side nav icon<br>5. Click logout<br>6. Log in with a second valid account |

![image](https://user-images.githubusercontent.com/19809794/104792812-bd93d000-57da-11eb-8829-9b79f3d277df.png)

**Comment by RichardZapanta** [comment]
This is an invalid bug as this is not the scope of the previous two sprints. The resetting of the board falls under the gameplay feature which will be implemented on this sprint. Thank you!

**Comment by counterPH** [comment]
Bug is invalid.
