### ISSUE TITLE
[CSS-Responsiveness] ‘How To Play’ Screen Small Window Size Broken Display 

### ISSUE THREAD

**Issue by LouisD69** [MaikaRenee/check-with-me#91]
|  
-- | --
ID | CR-01
Title | [CSS Responsiveness] ‘How To Play’ Screen Small Window Size Broken Display 
Reporter | Team Rocket (Dela Cruz)
Date | Jan 15, 2021
Environment | Windows 10 - Microsoft Edge
Priority level | Low

**Steps to reproduce:** 
1. Open the ‘How To Play’ screen
2. Set the window size to 375 x 667 (recommend using Window Resizer extension in Chrome/Edge, manual resize will also work)
3. Scroll down to Game Mechanics (refer to screenshot)

**Expected Results:** 
The components of the page will resize in such way that the contents are displayed properly

**Actual  Results:** 
The components did not resize and display the contents properly.

**Screenshot:**
![image](https://user-images.githubusercontent.com/61369999/104810257-3a03ce80-582e-11eb-9395-9d3cdc309f8e.png)

**Comment by RichardZapanta** [comment]
This is a valid bug. Our devs agree to make this webpage responsive. Thank you!
