### ISSUE TITLE
Timer does not stop despite the end of the game

### ISSUE THREAD

**Issue by geosefuy** [MaikaRenee/check-with-me#94]
When a game ends either via no moves left or no more remaining checker pieces, the timer does not stop for the player who lost.

Bug Report: https://docs.google.com/document/d/1Hw5VgRFC1m8Rqa4rqJMRwwFW35aP6V2fGH792XmFUUg/edit

**Comment by geosefuy** [comment]
To be resolved in Timer ticket.

**Comment by counterPH** [comment]
Issue is resolved.
